# Generated by Django 4.2.2 on 2023-06-14 17:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_open', models.TimeField(null=True)),
                ('mon_close', models.TimeField(null=True)),
                ('tue_open', models.TimeField(null=True)),
                ('tue_close', models.TimeField(null=True)),
                ('wed_open', models.TimeField(null=True)),
                ('wed_close', models.TimeField(null=True)),
                ('thu_open', models.TimeField(null=True)),
                ('thu_close', models.TimeField(null=True)),
                ('fri_open', models.TimeField(null=True)),
                ('fri_close', models.TimeField(null=True)),
                ('sat_open', models.TimeField(null=True)),
                ('sat_close', models.TimeField(null=True)),
                ('sun_open', models.TimeField(null=True)),
                ('sun_close', models.TimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(15, 'Maximum quantity reached')]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (2, 'Submitted'), (3, 'Accepted'), (4, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=75)),
                ('address', models.TextField(max_length=150)),
                ('out_of_schedule_close', models.BooleanField(default=False)),
                ('available_items', models.ManyToManyField(to='order.menuitem')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.businesshours')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.store'),
        ),
    ]
