# Generated by Django 4.2.2 on 2023-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_businesshours_orderitem_quantity_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.TextField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.TextField(max_length=75, unique=True),
        ),
    ]
