# Generated by Django 4.2.2 on 2023-06-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_menuitem_name_alter_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.TextField(default='MDT', max_length=3),
            preserve_default=False,
        ),
    ]
