# Generated by Django 4.2.2 on 2023-06-14 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_store_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='timezone',
        ),
        migrations.AddField(
            model_name='store',
            name='utc_offset',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(14, 'Invalid utc offset'), django.core.validators.MinValueValidator(12, 'Invalid utc offset')]),
        ),
    ]
