# Generated by Django 4.2.2 on 2023-06-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_store_timezone_store_utc_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='utc_offset',
            field=models.TextField(default='UTC', max_length=30),
        ),
    ]
