# Generated by Django 4.2.2 on 2023-06-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_address_menuitem_ingredients_order_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
    ]
