# Generated by Django 4.2.2 on 2023-06-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.address'),
            preserve_default=False,
        ),
    ]
