# Generated by Django 4.2.2 on 2023-06-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_ordermethod_store_order_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermethod',
            name='method',
            field=models.TextField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Pickup'),
        ),
    ]
