# Generated by Django 4.2.2 on 2023-06-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_ordermethod_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_method',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='order.ordermethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermethod',
            name='method',
            field=models.TextField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Pickup', unique=True),
        ),
    ]
