# Generated by Django 4.2.2 on 2023-06-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_order_method_alter_ordermethod_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.TextField(choices=[('Pizza', 'Pizza'), ('Salad', 'Salad'), ('Appetizer', 'Appetizer')], default='Pizza'),
        ),
    ]
